# Generated by Django 6.0.6 on 2026-07-19 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_create_default_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('party_type', models.CharField(choices=[('LEGAL_ENTITY', 'Legal Entity'), ('INDIVIDUAL', 'Individual')], default='LEGAL_ENTITY', max_length=20)),
                ('business_id', models.CharField(max_length=20)),
                ('party_code', models.CharField(blank=True, max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='masterdata.organization')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'party_code'), name='uq_party_party_code'), models.CheckConstraint(condition=models.Q(('party_type__in', ['LEGAL_ENTITY', 'INDIVIDUAL'])), name='chk_party_party_type')],
            },
        ),
    ]
