# Generated by Django 6.0.6 on 2026-07-20 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('personal_id', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(editable=False, max_length=200)),
                ('short_name', models.CharField(editable=False, max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='masterdata.organization')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
    ]
