# Generated by Django 6.0.6 on 2026-07-23 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRelationship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('relationship_type', models.CharField(choices=[('BIZ_STRUCTURE', 'Business Composition'), ('BIZ_OWNERSHIP', 'Ownership Relationship'), ('CORP_GOV', 'Director Appointment'), ('EMPLOYMENT', 'Employment Agreement'), ('SALES', 'Sales Agreement'), ('PURCHASE', 'Supply Agreement'), ('SERVICE', 'Service Agreement'), ('LOAN', 'Loan Agreement'), ('INSURANCE', 'Insurance Policy'), ('LEASE', 'Lease Agreement')], max_length=32)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_relationships', to='masterdata.organization')),
            ],
            options={
                'verbose_name': 'Business Relationship',
                'verbose_name_plural': 'Business Relationships',
                'ordering': ['relationship_type', 'effective_from', 'id'],
            },
        ),
    ]
