# Generated by Django 6.0.6 on 2026-07-25 06:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_businessrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRelationshipParticipant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role_type', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('COMPANY', 'Company'), ('PARTNER', 'Partner'), ('DIRECTOR', 'Director'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('PROVIDER', 'Provider'), ('LENDER', 'Lender'), ('INSURER', 'Insurer'), ('LESSOR', 'Lessor')], max_length=32)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('business_relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='masterdata.businessrelationship')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_participations', to='masterdata.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_participations', to='masterdata.party')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationship_participations', to='masterdata.person')),
            ],
            options={
                'verbose_name': 'Business Relationship Participant',
                'verbose_name_plural': 'Business Relationship Participants',
                'ordering': ['business_relationship', 'role_type', 'id'],
            },
        ),
    ]
