# Generated by Django 6.0.6 on 2026-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_businessrelationshipparticipant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='uq_party_party_code',
        ),
        migrations.RemoveField(
            model_name='businessrelationship',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('party_code',), name='uq_party_party_code'),
        ),
        migrations.RemoveField(
            model_name='party',
            name='organization',
        ),
    ]
