# Generated by Django 6.0.6 on 2026-07-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0007_remove_party_uq_party_party_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party', to='masterdata.person'),
        ),
    ]
