# Generated by Django 6.0.6 on 2026-08-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_asset_product_project_roletype_party_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='root_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdepartments', to='masterdata.department', verbose_name='Root Department'),
        ),
    ]
